[project]
name = "confer-parse-dub"
# Version follows semantic versioning <https://semver.org/>.
version = "0.0.0-dev.1"
description = ""
authors = [
    {name = "James Fogarty",email = "jayfo@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.14,<4.0"

[tool.poetry]
packages = [
    {include = "confer_parse_dub", from = "src"},
    {include = "paths.py", from = "."},
]

[tool.poetry.dependencies]
pydantic = "^2.12.5"
questionary = "^2.1.0"
ruamel-yaml = "^0.18.10"
titlecase = "^2.4.1"

[tool.poetry.group.dev.dependencies]
# ^ allows all minor and patch releases.
#   Example: ^1.2.3 will match 1.x.x versions >=1.2.3 but <2.0.0.
# ~ allows only patch releases.
#   Example: ~1.2.3 will match versions >=1.2.3 but <1.3.0.
fogies = {version = "^0.0.0-dev.2", allow-prereleases = true}
basedpyright = "^1.36.1"
black = "~25.12.0" # Black does not semver.
invoke = "^2.2.1"
isort = "^7.0.0"
pytest = "^9.0.2"

[tool.basedpyright]
typeCheckingMode = "recommended"
pythonVersion = "3.14"
include = ["paths.py", "src", "tasks", "tests"]
allowedUntypedLibraries = ["invoke"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
